# Contact.create!([
#   {first_name: "Adrian", last_name: "Emard", email: "kendra@lowe.info", phone_number: "1-769-618-5822 x9578", middle_name: "Tyrique", bio: "Minus id ad aliquid distinctio et laborum voluptatem. Totam quia quae cupiditate beatae quisquam non. Minus et nisi est ut odit commodi."},
#   {first_name: "Cassie", last_name: "Pfeffer", email: "danial_bernier@nader.com", phone_number: "658.592.7891 x78959", middle_name: "Russ", bio: "Quam in maiores repudiandae voluptatum consectetur. Dolorem totam quo voluptatibus consequatur. Labore rem molestiae officia aut id qui omnis."},
#   {first_name: "Roberta", last_name: "Jast", email: "arnold@murphylegros.org", phone_number: "106-403-0854 x64423", middle_name: "Luis", bio: "Autem quos voluptatum aut nihil ullam fugit dolores. Accusamus repellat id est eum minima debitis omnis. Ut quod beatae tenetur fugit neque aut aperiam."},
#   {first_name: "Alyce", last_name: "Armstrong", email: "geraldine@deckow.io", phone_number: "153.512.3564 x1386", middle_name: "Titus", bio: "In rerum quis. Incidunt sed autem est reiciendis pariatur atque. Aut quidem facere tempora soluta autem rerum."},
#   {first_name: "Carey", last_name: "Bednar", email: "ibrahim@trantow.biz", phone_number: "138.043.4447 x148", middle_name: "Gunnar", bio: "Minus ipsa vel. Reprehenderit et beatae dolor iste officiis labore. Eos odio ducimus iusto."},
#   {first_name: "Jovani", last_name: "Spinka", email: "jayne_berge@armstrong.biz", phone_number: "1-314-452-1405", middle_name: "Kennedy", bio: "Blanditiis odit dolorem eos perferendis ut et consequuntur. Non repellendus omnis. Neque reiciendis et quisquam ea. Mollitia quo nulla odit."},
#   {first_name: "Antoinette", last_name: "Koss", email: "bernice@schaden.io", phone_number: "885-882-6823", middle_name: "Maverick", bio: "Et voluptatem numquam dolorem soluta eaque. Ut sed nostrum ipsum. Sed sequi eos deserunt eos eum. Molestiae et impedit consectetur ratione ducimus."},
#   {first_name: "Gerda", last_name: "Haag", email: "april@monahan.name", phone_number: "1-336-963-5663 x57621", middle_name: "Nelda", bio: "Quae assumenda doloremque. Est consequuntur optio nam hic quo quo error. Et ea quibusdam quia molestiae optio omnis."},
#   {first_name: "Bernadette", last_name: "Gutmann", email: "novella.hintz@powlowski.co", phone_number: "957.392.2800", middle_name: "Kenna", bio: "Sunt possimus nulla nobis accusamus. Quod quisquam officia rem earum. Placeat qui atque consequatur iste deleniti. Corrupti et quas iure reiciendis porro. Qui hic eum."},
#   {first_name: "Lewis", last_name: "Konopelski", email: "deborah.hettinger@bergstrom.net", phone_number: "(705) 464-0904", middle_name: "Helga", bio: "Veritatis esse eligendi corporis ratione et eum. Ut nostrum repellendus quidem est sed aut perferendis. Et porro placeat id nobis consequatur et. Id et velit. Quia occaecati officia velit voluptatibus consequatur."},
#   {first_name: "Destiney", last_name: "Spencer", email: "brooklyn@schuster.org", phone_number: "280.861.6406 x16096", middle_name: "Ova", bio: "Earum eum minus rerum sint. Omnis voluptas occaecati quis aut. Repudiandae occaecati repellat cumque adipisci ullam qui a. Iste iure rerum excepturi asperiores."},
#   {first_name: "Corbin", last_name: "Howe", email: "lenora.turcotte@weinatemmerich.biz", phone_number: "1-871-911-0952 x9757", middle_name: "Retha", bio: "Assumenda et cupiditate enim autem autem harum omnis. Vitae quaerat vel sint sit aut aut optio. Cum qui animi repellat alias velit. Sit laudantium non ut temporibus et dolor aut."},
#   {first_name: "Jordane", last_name: "Lemke", email: "brionna.mraz@lakin.org", phone_number: "267-898-3899", middle_name: "Calista", bio: "Debitis et eos corrupti aut qui asperiores. Ut facilis earum sapiente ipsa. In similique aut. Libero nobis qui nulla fugit omnis animi laboriosam."},
#   {first_name: "Cielo", last_name: "Marquardt", email: "roscoe_mraz@roberts.biz", phone_number: "224.833.9288 x50030", middle_name: "Trey", bio: "Consequatur dolor repellendus qui ut ut. Minus voluptatem dignissimos neque velit vitae vel non. Itaque quasi necessitatibus sit ut architecto asperiores suscipit. Soluta et a enim porro."},
#   {first_name: "Finn", last_name: "Nader", email: "delia@glover.co", phone_number: "(881) 771-8058 x104", middle_name: "Selina", bio: "Facere est placeat reprehenderit. Autem vel laboriosam. Odio suscipit rerum voluptas ex est ratione consequatur. Consequatur sequi eos neque suscipit dicta."},
#   {first_name: "Jerod", last_name: "Ferry", email: "jeika_mueller@bins.io", phone_number: "193-924-2345 x519", middle_name: "Napoleon", bio: "Unde eos consequatur porro. Quasi commodi quia consequatur dolor delectus excepturi. Pariatur esse illo officia omnis eos facilis."},
#   {first_name: "Jewell", last_name: "Bahringer", email: "izaiah.wisozk@johns.biz", phone_number: "1-401-312-9966", middle_name: "Krystal", bio: "Laboriosam commodi distinctio sint. In magni enim id eum porro eveniet vel. Sit est ea qui voluptas. Qui pariatur quibusdam magni odit iure odio repudiandae."},
#   {first_name: "Josefa", last_name: "Ryan", email: "sasha@daugherty.info", phone_number: "1-294-057-6825", middle_name: "Anabelle", bio: "Molestiae sint vitae nihil aut necessitatibus eligendi. Cupiditate ut nemo perferendis perspiciatis quis placeat. Soluta cum ipsa. Voluptatum laboriosam possimus voluptas perferendis minus. Temporibus perspiciatis dolores voluptatibus eum voluptas."},
#   {first_name: "Ariane", last_name: "Lockman", email: "ana.heidenreich@koepp.net", phone_number: "(186) 309-8842 x5305", middle_name: "Abe", bio: "Qui et aperiam nam ducimus distinctio saepe sed. Fuga minus qui voluptate nemo. Mollitia cumque accusamus."},
#   {first_name: "Alexandrea", last_name: "Bashirian", email: "moriah_toy@treutelstroman.name", phone_number: "1-291-951-0399 x519", middle_name: "Willie", bio: "Sit enim modi molestias dolorem velit. Id rerum numquam consequatur. Quibusdam animi minima inventore nulla eaque. Delectus voluptatem nemo quia quo quisquam aut. Et enim totam voluptatem."},
#   {first_name: "Margarett", last_name: "Schuppe", email: "christopher@wehnerernser.info", phone_number: "807-957-8269", middle_name: "Providenci", bio: "Quia quia expedita ad nisi hic. Incidunt sapiente molestias neque quia facere ducimus. Minima aliquid sunt qui quod. Ab delectus distinctio quas harum aperiam est. Ad debitis doloremque."},
#   {first_name: "Kelly", last_name: "Koepp", email: "margaretta@metz.name", phone_number: "(250) 121-7630", middle_name: "Alivia", bio: "Voluptas quod facere soluta officia quis. Laudantium exercitationem et aliquid consequuntur consequatur. Ut nemo perferendis necessitatibus quod consequuntur culpa est. Ut pariatur distinctio dolores inventore nihil culpa quisquam."},
#   {first_name: "Joshua", last_name: "Reinger", email: "ryan@parisian.net", phone_number: "160.732.6794", middle_name: "Shana", bio: "Sit natus asperiores sunt a aspernatur deserunt dolorem. Harum distinctio et excepturi. Ad nihil id consectetur occaecati eos assumenda iure. Aut et vitae ullam fugiat illum odit necessitatibus. Unde et hic eum quo."},
#   {first_name: "Kattie", last_name: "Herman", email: "nat_cole@mohrlubowitz.io", phone_number: "326.290.6343 x238", middle_name: "Gayle", bio: "Consectetur minus temporibus ut illo et vel consequatur. Quaerat animi minus quibusdam ut molestias nesciunt. Deserunt aut repellendus deleniti ut nesciunt praesentium quia."},
#   {first_name: "Russell", last_name: "Koelpin", email: "lon.haag@metz.info", phone_number: "117.374.4534", middle_name: "Makenna", bio: "Velit eum porro vero nulla. Quas voluptas ratione id. Consequatur sit eius molestias autem. Quos excepturi et eligendi voluptas. Earum ipsa dignissimos."},
#   {first_name: "Raheem", last_name: "Hudson", email: "margaret@grimes.biz", phone_number: "957-317-9714 x01959", middle_name: "Scotty", bio: "Odio ut cupiditate voluptate eum omnis voluptas. Soluta dolorum omnis. Quasi nam et sunt."},
#   {first_name: "Kelly", last_name: "Wilderman", email: "houston@runte.org", phone_number: "492.714.8443 x4578", middle_name: "Stephanie", bio: "Dolorum quo delectus. Laborum corporis libero. Animi rem voluptas officiis. Est ullam dolorem officiis non voluptatem enim placeat."},
#   {first_name: "Delphine", last_name: "Bailey", email: "julio_abernathy@strosinmueller.io", phone_number: "619.890.9772 x5806", middle_name: "Shane", bio: "Et facilis explicabo iusto voluptas laudantium expedita. Placeat quia enim asperiores. Occaecati perspiciatis omnis nesciunt necessitatibus veniam velit."},
#   {first_name: "Geo", last_name: "Emard", email: "lenore@spinka.io", phone_number: "323-802-2125 x39802", middle_name: "Trace", bio: "Error aspernatur ea harum tempore provident. Voluptatem mollitia consequatur consequatur numquam suscipit. Repudiandae ea inventore ut quos mollitia totam voluptatibus. Modi totam qui similique. Dignissimos quod dolorem consequatur qui autem necessitatibus."},
#   {first_name: "Jasen", last_name: "Quigley", email: "liliana@dickinsonsatterfield.com", phone_number: "1-266-495-7732 x26732", middle_name: "Johnny", bio: "Qui omnis molestiae rerum incidunt quisquam dolor consequatur. Culpa repudiandae omnis. Optio mollitia molestiae necessitatibus aut molestiae. Et consectetur in quas reiciendis dolor ut. Et culpa architecto nisi accusamus."},
#   {first_name: "Loma", last_name: "Kunze", email: "tanya@pollich.biz", phone_number: "1-707-244-8342 x7740", middle_name: "Theodora", bio: "Nisi officiis reiciendis dolore nulla. Quis qui aliquam quo. Et excepturi qui dignissimos nulla incidunt consequatur. Enim adipisci omnis minima omnis cum voluptas."},
#   {first_name: "Lelia", last_name: "Connelly", email: "rhiannon.dooley@ferry.com", phone_number: "170-532-3005 x19535", middle_name: "Karen", bio: "Modi sit odit sit sunt aspernatur. Omnis aut possimus quis ipsum sunt magnam. Odit reiciendis omnis quis ut doloribus. Culpa est nostrum eos. Repellat iusto qui nesciunt."},
#   {first_name: "Marley", last_name: "Kiehn", email: "dell@mosciski.io", phone_number: "142-309-2654 x81605", middle_name: "Esmeralda", bio: "Enim facere sit non eos distinctio. Atque est natus corrupti. Quis modi qui. Aut commodi voluptatem sint quae perspiciatis mollitia ut. Veniam ipsum error fuga qui accusamus aspernatur impedit."},
#   {first_name: "Ignacio", last_name: "Bernier", email: "muhammad_hoppe@hagenes.net", phone_number: "695-561-8762", middle_name: "Kevon", bio: "Dolor est nihil quia impedit. Molestiae soluta placeat commodi non officiis. Iste culpa ea impedit et qui numquam. Sunt omnis eaque et error totam nihil excepturi. Occaecati odit quia id molestiae."},
#   {first_name: "Marian", last_name: "Glover", email: "alfonzo_west@deckowbauch.name", phone_number: "1-413-357-0563", middle_name: "Sunny", bio: "Amet sapiente minima ut voluptatem. Eos laudantium dolore quae. Ipsum dignissimos doloribus aliquam dicta. Alias vel et nihil debitis ducimus sed. Et ut amet quasi."},
#   {first_name: "Zella", last_name: "McLaughlin", email: "gerda@schneider.io", phone_number: "(842) 300-3162 x6266", middle_name: "Zena", bio: "Illo assumenda sequi in rerum in ipsa aut. Autem repudiandae id. Laboriosam aliquam ut eum recusandae."},
#   {first_name: "Lonzo", last_name: "Pouros", email: "lucio_rogahn@effertz.name", phone_number: "1-500-000-0778", middle_name: "Mallie", bio: "Nam fugit distinctio ipsam eum et mollitia. Magni harum distinctio repellat fugit et. Voluptatem unde ex consequatur corrupti numquam facilis distinctio."},
#   {first_name: "Marcelo", last_name: "Eichmann", email: "jacquelyn@leannon.org", phone_number: "1-547-325-2861 x848", middle_name: "Gertrude", bio: "Expedita dolore consequatur. Ut rerum vero voluptatum numquam sed quas consequatur. Aut et qui doloribus. Vel sapiente consequatur sint."},
#   {first_name: "Adriel", last_name: "Altenwerth", email: "thaddeus@dickens.org", phone_number: "(718) 764-3864", middle_name: "Donny", bio: "Accusamus voluptas eum dolorum. Accusamus consequatur incidunt. Voluptatibus neque quod harum. Quisquam voluptatum atque. Exercitationem impedit magni consequuntur dolor ut."},
#   {first_name: "Eliane", last_name: "Reichert", email: "randall_collins@schmidt.co", phone_number: "481.128.3971", middle_name: "Clemens", bio: "Aut quis qui labore. Sapiente maxime quos et molestiae. Qui magni aut laboriosam autem nam ea. Praesentium iusto numquam doloremque voluptatibus non. Itaque ea quaerat id distinctio."},
#   {first_name: "Anya", last_name: "Daugherty", email: "carolina@watsicawindler.net", phone_number: "361-534-6074", middle_name: "Dallin", bio: "Adipisci nihil vel placeat natus. Unde provident ut repellendus numquam delectus. Dolorem tenetur inventore numquam quae eveniet magnam. Beatae sint doloribus voluptas aliquid odio saepe reprehenderit. Impedit saepe tempora consectetur labore cumque nihil."},
#   {first_name: "Kian", last_name: "Jast", email: "virginia@oberbrunner.co", phone_number: "673.655.8861 x162", middle_name: "Eloisa", bio: "Sed non vitae dicta aut eius unde. Corporis enim fugit in dolores quam non sapiente. Quam adipisci omnis et alias molestias enim cupiditate."},
#   {first_name: "Andy", last_name: "Kautzer", email: "lou@corwin.com", phone_number: "194.748.7239 x41448", middle_name: "Callie", bio: "Fuga qui est saepe vel laudantium. Molestiae temporibus ex maxime nam corrupti doloribus. Repudiandae et nihil consequuntur ea unde tempore error. Neque non molestiae aut est laboriosam ex. Officiis vel est cum voluptatem omnis."},
#   {first_name: "Hunter", last_name: "Ledner", email: "joel@schultzkling.co", phone_number: "386.066.4912 x32206", middle_name: "Danyka", bio: "Vero est distinctio dolor quae aut. Eum optio iste. Eligendi blanditiis quo quia consectetur eum provident. Suscipit aut quo accusantium autem nulla quos."},
#   {first_name: "Brown", last_name: "Gutkowski", email: "eva@feest.name", phone_number: "646.093.2148", middle_name: "Destinee", bio: "Eveniet natus eum. Temporibus maiores eveniet rerum placeat autem sapiente quidem. Vero enim dolores porro reiciendis unde sequi officiis."},
#   {first_name: "Humberto", last_name: "Barrows", email: "caandra@ernserschowalter.info", phone_number: "(266) 271-5534", middle_name: "Kris", bio: "Molestiae ut necessitatibus qui rerum incidunt sed iusto. Ut temporibus a. Laudantium sint dolores a placeat corporis."},
#   {first_name: "Randall", last_name: "Heaney", email: "clementine_spencer@wuckertjacobs.biz", phone_number: "1-492-297-8808", middle_name: "Art", bio: "Tempora fugiat voluptatem repellendus ducimus quam. In iusto voluptatum. Et suscipit nobis nemo ducimus reiciendis dolorem sed. Ut quis eum quis qui et reprehenderit. Dolorum recusandae reiciendis consequuntur assumenda beatae hic."},
#   {first_name: "Keenan", last_name: "Koelpin", email: "pamela.swaniawski@stromanlang.io", phone_number: "271.276.1928", middle_name: "Darrel", bio: "Libero et ab odit. Animi quia illo consectetur recusandae quidem quis fuga. Vel non qui autem blanditiis eius quo temporibus. Beatae placeat perspiciatis dolorem rerum consequatur ut consequuntur."},
#   {first_name: "Jeffery", last_name: "Huels", email: "lora@rutherford.io", phone_number: "(359) 093-8917", middle_name: "Asha", bio: "Totam quod assumenda architecto. Ut eius voluptas optio similique vero. Id et qui veritatis minus earum aut. Vel eos reprehenderit tenetur."},
#   {first_name: "Lee", last_name: "Klocko", email: "carli_lueilwitz@dach.co", phone_number: "983-239-8345 x487", middle_name: "Ryann", bio: "Ipsum non laborum sed molestias dolores numquam incidunt. Modi deserunt voluptatibus earum quia rem eos. Ut inventore non sed possimus unde."},
#   {first_name: "Kasey", last_name: "Wehner", email: "thea.abbott@wilkinson.net", phone_number: "192-594-8654 x5319", middle_name: "Damion", bio: "Et cum ipsam quae debitis a. Et deleniti provident aperiam sit. Sunt ut et eos."},
#   {first_name: "Baby", last_name: "Fahey", email: "regan@luettgen.name", phone_number: "108.110.2674", middle_name: "Jaydon", bio: "Error consequatur quia delectus aut quia. Quod molestias accusantium fugit eaque corrupti inventore alias. Ut est quasi et voluptatem amet. Sint voluptatum odio et aut magnam. Aut voluptatum quos."},
#   {first_name: "amy", last_name: "johnson", email: "aosdjfa", phone_number: "097654", middle_name: "Enid", bio: "Et dolor velit. Vitae est explicabo aliquam inventore. At beatae vero illum voluptatum explicabo."},
#   {first_name: "Arvel", last_name: "Douglas", email: "berneice_stokes@beerbradtke.biz", phone_number: "825-639-7940", middle_name: "Bruce", bio: "Aut non nihil quo iusto. Distinctio eius autem id laborum illo in. Repudiandae rerum consequuntur a laborum. Mollitia culpa unde numquam omnis qui cumque."},
#   {first_name: "Cameron", last_name: "Connelly", email: "drew_harris@ebert.name", phone_number: "629.918.8498", middle_name: "Otto", bio: "Repellendus dolor a possimus. Laborum nobis mollitia pariatur praesentium eaque voluptatibus voluptate. Et tempore inventore est et corrupti."},
#   {first_name: "Ewald", last_name: "Quigley", email: "cristian.jacobson@pfannerstill.net", phone_number: "384-723-9251 x6454", middle_name: "Anderson", bio: "Eveniet omnis doloremque vero deleniti veritatis quam praesentium. Placeat nihil mollitia porro et repellendus nobis. Illum vitae laborum pariatur doloribus."},
#   {first_name: "Jazlyn", last_name: "Lynch", email: "whitney.stanton@klein.co", phone_number: "1-258-463-1583 x0394", middle_name: "Heaven", bio: "Et sunt aliquid. Ea nisi aut in. Veritatis facilis odit tempore voluptatum est ut."},
#   {first_name: "Ashlee", last_name: "Kuhlman", email: "tatyana.nikolaus@kubdouglas.info", phone_number: "391-595-6221 x1927", middle_name: "Maxine", bio: "Quia rerum nisi dolores voluptas possimus sed. Minus aut voluptatem perferendis voluptas quasi rerum ut. Et aut eveniet aliquam vel rerum asperiores."},
#   {first_name: "Kelly", last_name: "Herman", email: "robbie@kohler.biz", phone_number: "1-567-095-7059", middle_name: "Clemmie", bio: "Aut laudantium et assumenda. Voluptate qui est maiores aspernatur quae dolorem soluta. Quaerat esse id aspernatur qui illo quam. Error alias omnis unde dolore accusantium magnam. Voluptatem perferendis nostrum eos."},
#   {first_name: "Reyes", last_name: "Blanda", email: "dorothy.white@gleason.biz", phone_number: "840-598-6368 x86152", middle_name: "Rhoda", bio: "Accusantium laboriosam molestiae. Molestiae sequi neque. Perspiciatis aut repellendus atque ipsum. Sed aut consequatur est eos in aut rerum."},
#   {first_name: "Brandon", last_name: "Champlin", email: "jaclyn@cartwrighthermiston.co", phone_number: "1-628-631-2042 x7462", middle_name: "Dudley", bio: "Architecto magni voluptatum. Quia corrupti qui magnam minima reiciendis numquam repudiandae. In adipisci nihil aliquam error corrupti illo occaecati. Et eum recusandae impedit."},
#   {first_name: "Francesco", last_name: "Murazik", email: "alize.paucek@crist.net", phone_number: "251.581.1780", middle_name: "Amy", bio: "Est minima inventore sunt autem aut. Nostrum quod et voluptatem. Rerum nam qui aut. Ut cum quia sit in. Libero ipsa sed."},
#   {first_name: "Ari", last_name: "Beahan", email: "madelyn@gibson.co", phone_number: "1-499-392-2151", middle_name: "Dorothy", bio: "Optio dignissimos blanditiis sit consectetur eveniet nesciunt nihil. Dolores ipsa aperiam fugiat. Veritatis non enim mollitia quidem molestias sint vero. Rem eligendi error. Accusantium expedita maiores quisquam."},
#   {first_name: "Reva", last_name: "Marks", email: "lauryn@mann.co", phone_number: "373.494.5401", middle_name: "Chris", bio: "Sed optio est natus autem. Eius dolorem ut distinctio alias reprehenderit soluta et. Modi ipsum odio iste molestiae perspiciatis. Tempore distinctio aut rerum eaque."},
#   {first_name: "Avis", last_name: "Herman", email: "jeramy.howell@douglas.info", phone_number: "(206) 511-7138 x1889", middle_name: "Chadd", bio: "Ab sit omnis. Quae rerum quis quo quod veritatis. Saepe labore quisquam et eos porro. Quam deserunt et distinctio ipsam dolor et doloribus. Hic sed nobis consequuntur optio dolores minus ducimus."},
#   {first_name: "Janet", last_name: "Wolff", email: "turner@farrell.org", phone_number: "1-212-165-0608 x725", middle_name: "Marianne", bio: "Vel voluptate eveniet suscipit blanditiis fugit. Et dignissimos in expedita accusantium doloribus cumque velit. Nisi voluptate quas distinctio. Blanditiis repellat aliquam consequatur laboriosam laudantium quo."},
#   {first_name: "Ramon", last_name: "Tromp", email: "bert.goodwin@medhurst.net", phone_number: "1-720-511-2124 x44782", middle_name: "Yasmin", bio: "Assumenda et cumque labore ipsam. Adipisci ducimus iste distinctio. Praesentium vel voluptas sed. Molestiae optio qui perferendis sit provident dolorum voluptate. Temporibus est repellendus nihil ut."},
#   {first_name: "Janick", last_name: "Dickens", email: "leonard.ko@cummeratawolf.co", phone_number: "1-636-649-5152 x193", middle_name: "Jaeden", bio: "Voluptate non assumenda fuga. Qui eos id iusto beatae sit laborum. Voluptate odit velit occaecati illo nihil. Quo et eaque suscipit omnis vel. Illum natus dignissimos autem corporis sed vel."},
#   {first_name: "Mandy", last_name: "Kris", email: "josue_mcglynn@connelly.com", phone_number: "416.161.2342 x6893", middle_name: "Iva", bio: "Iure sed sapiente sed praesentium repellat. Repellendus sunt voluptatem expedita minima velit. Cum dolorem et ut aut."},
#   {first_name: "Yvonne", last_name: "Lindgren", email: "jadyn@corwin.io", phone_number: "279-771-7201", middle_name: "Jakob", bio: "Quis aliquid nobis. Molestiae libero sit minima sint reiciendis ratione. Asperiores sapiente labore maxime fugit. Quaerat soluta non cum dolorem ut natus."},
#   {first_name: "Roger", last_name: "Langosh", email: "sharon.crooks@batzoberbrunner.net", phone_number: "197.773.9484 x68744", middle_name: "Bertram", bio: "Rerum sequi expedita recusandae. Harum aliquid ducimus cum quia rerum suscipit. Temporibus eligendi ut voluptas molestias quaerat blanditiis. Neque quasi sed tempora dolorem quaerat. Exercitationem quis maiores."},
#   {first_name: "Marlin", last_name: "Klein", email: "ubaldo_murazik@jacobson.org", phone_number: "684-597-1655 x898", middle_name: "Santina", bio: "Vero sed magni ut saepe deleniti nulla aliquid. Quidem totam rerum in deserunt vel et. Aperiam quia ea sunt blanditiis. Repudiandae quas sunt. Aut illum unde."},
#   {first_name: "Karl", last_name: "Tillman", email: "carson.hammes@langosh.name", phone_number: "(646) 968-9315 x55649", middle_name: "Cade", bio: "Sit quos laboriosam. Quia suscipit quibusdam quod. Voluptates autem ratione ad placeat ut. Id non sequi atque ratione corrupti veritatis."},
#   {first_name: "Blake", last_name: "Raynor", email: "edison@mertzmonahan.net", phone_number: "821.568.3775 x58722", middle_name: "Sandra", bio: "Dolorum soluta sunt ut eum voluptas mollitia veniam. Ipsam id voluptatibus. Magnam mollitia ullam dignissimos. Praesentium quisquam blanditiis asperiores est alias quod error."},
#   {first_name: "Roselyn", last_name: "Moen", email: "lavada_schaden@roobleuschke.co", phone_number: "(705) 347-2215 x1695", middle_name: "Rosendo", bio: "Voluptas accusamus placeat non voluptatum delectus eum dolor. Dolore est ut inventore incidunt. Nostrum eum minima sed."},
#   {first_name: "Christ", last_name: "Cartwright", email: "jenifer_kutch@littel.org", phone_number: "170.603.6292 x44896", middle_name: "Sydnee", bio: "Quisquam libero ipsa beatae quibusdam velit. Labore explicabo doloremque tempora. Modi cum deleniti. Sit possimus voluptatibus voluptate sunt deleniti aut. Perspiciatis et voluptas cupiditate."},
#   {first_name: "Violet", last_name: "Swaniawski", email: "lily_muller@shanahanbatz.io", phone_number: "810-715-3097 x963", middle_name: "Roger", bio: "Porro assumenda saepe voluptas vitae et. Alias eius aut deleniti. Nihil exercitationem ut doloribus tempora eaque et. Illo dolores minus laudantium at. Corporis et non."},
#   {first_name: "Jacklyn", last_name: "O'Reilly", email: "francisco@bartell.co", phone_number: "1-952-319-8055", middle_name: "Jaren", bio: "Sed recusandae nostrum corporis repudiandae. Architecto assumenda et labore sint aliquid earum aut. Accusamus distinctio odit et. Quisquam suscipit possimus earum. Nulla vero placeat molestias voluptatem maxime quod."},
#   {first_name: "Monique", last_name: "Lind", email: "keenan_bode@ferry.biz", phone_number: "1-888-040-4129 x913", middle_name: "Ali", bio: "Repellat quam saepe optio odit enim. Velit exercitationem eaque in tempore soluta accusamus. Beatae sit eveniet sequi veniam illum. Accusamus voluptatem qui. Voluptate impedit officiis non esse."},
#   {first_name: "Tierra", last_name: "Marks", email: "terrance.shields@reilly.co", phone_number: "594.662.0860 x68145", middle_name: "Cierra", bio: "Quod eos dolores qui dolores. Ipsum aliquam aliquid iusto non facilis placeat. Qui in dignissimos asperiores magni minima ratione. Ipsa et et cumque neque error. Vel iure odit cupiditate laudantium."},
#   {first_name: "Karen", last_name: "Deckow", email: "marlee.pfeffer@runte.net", phone_number: "411-722-1272 x936", middle_name: "Marietta", bio: "Sint voluptatem autem soluta quia. Molestiae velit nihil deserunt laborum praesentium. Veniam natus itaque praesentium autem nihil harum."},
#   {first_name: "Guillermo", last_name: "Heidenreich", email: "derrick_waters@thiel.biz", phone_number: "(200) 750-2176", middle_name: "Dariana", bio: "Temporibus adipisci sint esse quis enim. Quae quidem esse accusantium eius porro. Consectetur autem accusantium nesciunt et. Minima commodi aut dolorem."},
#   {first_name: "Brandt", last_name: "Quigley", email: "darryl.volkman@hintz.io", phone_number: "1-658-331-8931", middle_name: "Durward", bio: "Dolor ab deserunt ea incidunt ipsum. Error pariatur ab expedita dolorem. Et non aut assumenda dolorem odio voluptas a. Sint eligendi consequatur velit delectus facere veniam aut."},
#   {first_name: "Hyman", last_name: "Lemke", email: "devan@kshlerinsanford.io", phone_number: "(863) 019-9020", middle_name: "Ayla", bio: "Et vel eum voluptate inventore ipsam. Nobis harum voluptatem error aperiam esse aut. Molestiae officia officiis aut quia nisi."},
#   {first_name: "Clifton", last_name: "Bode", email: "stephan@rempelbernhard.name", phone_number: "931-787-3335 x82705", middle_name: "Sabryna", bio: "Asperiores corporis ullam. Officia itaque quod ipsa iste assumenda error. Omnis reprehenderit laboriosam animi sed magnam vero. Ipsum aut laudantium excepturi et voluptatem facere ut. Quos voluptatum quo."},
#   {first_name: "Haleigh", last_name: "Franecki", email: "pamela@lefflerwill.com", phone_number: "(522) 876-0814 x00305", middle_name: "Stone", bio: "Dolores deserunt quo quod rerum doloremque ipsa voluptatum. Laborum voluptatibus molestiae aut. Veritatis sed rerum minima officia velit provident vel."},
#   {first_name: "Rosemarie", last_name: "Schuster", email: "rudolph@robel.co", phone_number: "1-252-379-4597 x58106", middle_name: "Gwen", bio: "Iste esse reprehenderit quasi. Ratione recusandae consectetur delectus exercitationem quisquam facilis aliquid. Quis alias blanditiis et. At nobis cumque reiciendis atque."},
#   {first_name: "Macie", last_name: "Wisozk", email: "mose.gerlach@rohan.biz", phone_number: "1-116-307-1863", middle_name: "Princess", bio: "Suscipit saepe qui. Consequatur cumque dolore sit. Necessitatibus sit incidunt. Velit soluta cumque tempore sed deleniti sint."},
#   {first_name: "Sally", last_name: "Schimmel", email: "sylvan@wiza.org", phone_number: "1-345-527-9062", middle_name: "Leif", bio: "Ea itaque omnis id. Non quis minus et. Odio voluptas quasi sunt magni omnis aut."},
#   {first_name: "Shany", last_name: "Cassin", email: "bethel_prohaska@bruen.co", phone_number: "(744) 443-4791", middle_name: "Enos", bio: "Repellendus nihil aliquid quo. Necessitatibus voluptatem explicabo facilis laudantium doloremque. Voluptatibus et voluptate nostrum non delectus ut non. Harum officia fugit vero est corrupti."},
#   {first_name: "Breana", last_name: "Hirthe", email: "lamont.haley@stehr.net", phone_number: "545.735.0110 x7075", middle_name: "Dayne", bio: "Ab quod aliquam doloribus expedita similique eligendi. Neque nihil deleniti cumque ut quo explicabo. Nulla facilis placeat minima animi. Nihil necessitatibus quae explicabo in sed magni ipsum. Quod quis atque non quibusdam."},
#   {first_name: "Berenice", last_name: "Wyman", email: "ruthe.nienow@schmeleryost.com", phone_number: "1-265-631-8816", middle_name: "Ayla", bio: "Dicta suscipit ut dolorem est quia placeat repellendus. In numquam ullam et. Eius quisquam ut excepturi iste. Rerum est inventore dolor eos et fuga voluptatem."},
#   {first_name: "Gavin", last_name: "MacGyver", email: "annabell.west@keeling.net", phone_number: "(868) 135-5075", middle_name: "Laurine", bio: "Sunt nostrum nisi repellendus. Totam id cumque quidem expedita dolorem eius. Eos soluta facere ipsam ullam accusamus quas non."},
#   {first_name: "Isidro", last_name: "Koepp", email: "perry.heller@botsfordcain.name", phone_number: "182.109.2507 x805", middle_name: "Garrison", bio: "Ipsum deserunt aut ipsam illum. Sed nam temporibus dolorum et et inventore voluptatibus. Itaque quae in. Voluptatem ad autem. Voluptatem quidem cum."},
#   {first_name: "Braden", last_name: "Okuneva", email: "mireya.bayer@spinkadamore.co", phone_number: "(369) 248-3521 x4541", middle_name: "Violet", bio: "Dicta explicabo in excepturi voluptatem. Deleniti quo reiciendis magnam temporibus quia. Voluptas modi itaque reiciendis esse. Velit ut ut cupiditate dolor illo. Enim explicabo omnis omnis qui rerum."},
#   {first_name: "Hildegard", last_name: "White", email: "sadye.pfeffer@kiehn.name", phone_number: "1-544-042-1039 x748", middle_name: "Edwina", bio: "Delectus enim neque eveniet ut. Consequatur et nesciunt aut officia. Itaque magni et consectetur."},
#   {first_name: "Addison", last_name: "Batz", email: "emmy@krajcikreichel.name", phone_number: "1-590-432-1737 x44889", middle_name: "Ralph", bio: "Ut occaecati animi est et consequatur necessitatibus. Quae excepturi maxime tempora aut totam. In quia dolores recusandae sapiente voluptas molestiae natus."},
#   {first_name: "Maye", last_name: "Mayer", email: "leilani_reichert@kohler.net", phone_number: "935-710-0181 x058", middle_name: "Destinee", bio: "Non optio harum vel. Error laborum quam. Accusamus adipisci nihil. Qui eos est esse nisi distinctio delectus."},
#   {first_name: "Katelynn", last_name: "Wisozk", email: "garrick@rodriguezmitchell.info", phone_number: "886-180-8261", middle_name: "Evalyn", bio: "Sunt eius perspiciatis vitae quis est cum ducimus. Magni accusamus dolores dolore veniam molestiae quas. Occaecati deserunt aut ipsa harum."},
#   {first_name: "Ron", last_name: "Heaney", email: "zack@schneiderbogisich.biz", phone_number: "977-686-1335", middle_name: "Hilda", bio: "Corporis cupiditate id neque ad adipisci. Quo itaque autem voluptas dicta. Voluptates rerum et similique dolorum minus illum."},
#   {first_name: "Joe", last_name: "Bob", email: "emailemailemal", phone_number: "345678", middle_name: "Donny", bio: "Tempora facere dolore dolorem sed neque sunt et. Et consequatur temporibus. Atque minima est odio id."}
# ])


# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# 100.times do
#   contact = Contact.new(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, email: Faker::Internet.email, phone_number: Faker::PhoneNumber.phone_number)
#   contact.save
# end

# update everyone's middle name and bio so they aren't blank

# loop through `them all` => all the contacts. how do i get all the contacts (preferably in an array)? Contact.all
# loop through them
# modify them

# contacts = Contact.all

# contacts.each do |contact|
#   contact.middle_name = Faker::Name.first_name
#   contact.bio = Faker::Lorem.paragraph
#   contact.save
# end

groups = [1,2,3]

cg = ContactGroup.create(contact_id: 207, group_id: groups.sample)
cg = ContactGroup.create(contact_id: 208, group_id: groups.sample)
cg = ContactGroup.create(contact_id: 209, group_id: groups.sample)
cg = ContactGroup.create(contact_id: 210, group_id: groups.sample)
cg = ContactGroup.create(contact_id: 211, group_id: groups.sample)
cg = ContactGroup.create(contact_id: 212, group_id: groups.sample)
cg = ContactGroup.create(contact_id: 213, group_id: groups.sample)
